### ISSUE TITLE
Large Paper Sometimes Fails during POST /papers

### ISSUE THREAD

**Issue by danielBingham** [danielBingham/peerreview#179]
**Describe the bug**

Large papers will sometimes fail during the POST /papers calls.  Log output from one such failure:

```
Empty PDF!
2023-06-27T17:52:44.575Z:Session(22):error:: Error encountered.
error: insert or update on table "paper_versions" violates foreign key constraint "paper_versions_paper_id_fkey"
    at /home/dbingham/src/peerreview/packages/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PaperDAO.insertVersion (/home/dbingham/src/peerreview/packages/backend/daos/PaperDAO.js:369:32)
    at async PaperDAO.insertVersions (/home/dbingham/src/peerreview/packages/backend/daos/PaperDAO.js:331:13)
    at async PaperController.postPapers (/home/dbingham/src/peerreview/web-application/server/controllers/PaperController.js:477:13) {
  length: 283,
  severity: 'ERROR',
  code: '23503',
  detail: 'Key (paper_id)=(11) is not present in table "papers".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'paper_versions',
  column: undefined,
  dataType: undefined,
  constraint: 'paper_versions_paper_id_fkey',
  file: 'ri_triggers.c',
  line: '2528',
  routine: 'ri_ReportViolation'
}
POST /api/0.0.0/papers 500 10876.663 ms - 24

```

And postgres error:
```
2023-06-27 17:52:44.559 UTC [1085] ERROR:  insert or update on table "paper_versions" violates foreign key constraint "paper_versions_paper_id_fkey"
2023-06-27 17:52:44.559 UTC [1085] DETAIL:  Key (paper_id)=(11) is not present in table "papers".
2023-06-27 17:52:44.559 UTC [1085] STATEMENT:  
	            INSERT INTO paper_versions (paper_id, version, file_id, content, created_date, updated_date)
	                VALUES ($1, $2, $3, $4, now(), now())
	        
2023-06-27 17:52:44.574 UTC [1086] WARNING:  there is no transaction in progress
```

On resubmission the paper will successfully post at least some of the time.

**To Reproduce**

This is a heisenbug, so these steps will not consistently reproduce it.

1. Submit a new paper.  Upload a very large (50 mb+) file.
2. Submit the paper.

**Actual behavior**
What actually happened?

Paper fails to POST, error shown in the logs.

**Expected behavior**

Paper posts and user is taken to the drafts review screen.

**Comment by danielBingham** [comment]
Encountered this bug on stage with a much smaller (1 mb) paper.  Resubmitting allowed the paper to go through.  

Container logs showed:
```
POST /api/0.0.0/upload 200 674.762 ms - 293
GET /health 200 2.133 ms - -
DELETE /api/0.0.0/file/698b1a55-eaec-4405-aa1c-3649e6e6f494 200 34.917 ms - 49
GET /health 200 1.833 ms - -
GET /health 200 1.915 ms - -
POST /api/0.0.0/upload 200 2922.141 ms - 293
GET /health 200 2.741 ms - -
Warning: fetchStandardFontData: failed to fetch file "LiberationSans-Bold.ttf" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "LiberationSans-Regular.ttf" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "LiberationSans-Regular.ttf" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "FoxitSerifBold.pfb" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "FoxitSerif.pfb" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "FoxitSerifItalic.pfb" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "LiberationSans-Bold.ttf" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "FoxitSerif.pfb" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "FoxitSerifBold.pfb" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "LiberationSans-Regular.ttf" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "FoxitSerifItalic.pfb" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "LiberationSans-Italic.ttf" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
Warning: fetchStandardFontData: failed to fetch file "LiberationSans-Bold.ttf" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".
GET /health 200 39.084 ms - -
GET /health 200 40.767 ms - -
2023-06-28T15:38:22.051Z:Session(a864e8eb-9058-4ad1-a2a0-4140800fbfed):error:: Error encountered.
ControllerError: Paper 16 does not exist after insert!
    at PaperController.postPapers (/src/server/controllers/PaperController.js:488:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 500,
  type: 'server-error',
  data: {}
}
POST /api/0.0.0/papers 500 860.494 ms - 34
```

Database logs showed:
```
2023-06-28 15:38:22 UTC:10.0.4.64(52724):app@peer_review:[29659]:WARNING: there is no transaction in progress
```
